### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by flutterflies** [flutterflies/Ba#6]
I would like to change the license from the WTFPL to an MIT license, to be able to do this I need approval from all the contributors.

@skyem123 
@kabili207 
@bovarysme 
@cdamato 

Please post a comment on this issue saying either yes to no to the change

**Comment by kabili207** [comment]
Fine with me

**Comment by skyem123** [comment]
Fine by me!

**Comment by flutterflies** [comment]
closed by 10db3b9
